#!/bin/sh
exec 2>&1

# install framework tool shunt
PATH=../.bin:$PATH

# This script was borrowed from the runit-for-lfs project.
HIDD_ENABLE="false"
PAND_ENABLE="false"
DUND_ENABLE="false"
RFCOMM_ENABLE="false"
HIDD_OPTIONS=""
PAND_OPTIONS=""
DUND_OPTIONS=""

if [ -f "/etc/sysconfig/bluetooth" ]; then
  . /etc/sysconfig/bluetooth
fi
if [ "$HIDD_ENABLE" = "true" ]; then
  /usr/sbin/hidd "$HIDD_OPTIONS" 2>&1
fi
if [ "$RFCOMM_ENABLE" = "true" ]; then
  /usr/bin/rfcomm -f /etc/bluetooth/rfcomm.conf bind all || true
fi
if [ "$PAND_ENABLE" = "true" ]; then
  /usr/bin/pand "$PAND_OPTIONS" 2>&1
fi
if [ "$DUND_ENABLE" = "true" ]; then
  /usr/bin/dund "$DUND_OPTIONS" 2>&1
fi

# start the service
exec envdir ../.env envdir ./env sh -c 'exec $PRELAUNCH $DAEMON $DAEMONOPTS '

