#!/bin/sh

rm envdir && \
 ln -s /usr/bin/envdir ./envdir && \
  echo "$0: envdir reset"

rm envuidgid && \
 ln -s /usr/bin/envuidgid ./envuidgid && \
  echo "$0: envuidgid reset"

rm fghack && \
 ln -s /usr/bin/fghack ./fghack && \
  echo "$0: fghack reset"

rm pgrphack && \
 ln -s /usr/bin/pgrphack ./pgrphack && \
  echo "$0: pgrphack reset"

rm setlock && \
 ln -s /usr/bin/setlock ./setlock && \
  echo "$0: setlock reset"

rm setuidgid && \
 ln -s /usr/bin/setuidgid ./setuidgid && \
  echo "$0: setuidgid reset"

rm softlimit && \
 ln -s /usr/bin/softlimit ./softlimit && \
  echo "$0: softlimit reset"

rm tai64n && \
 ln -s /usr/bin/tai64n ./tai64n && \
  echo "$0: tai64n reset"

rm tai64nlocal && \
 ln -s /usr/bin/tai64nlocal ./tai64nlocal && \
  echo "$0: tai64nlocal reset"

echo -n "$0: setting up framework-specific grammar, "
echo "daemontools" > ../.env/FRAMEWORK
echo -n "svc" > ../.env/TOOLCMD
echo -n "svok" > ../.env/TOOLCHECK
echo -n "svstat" > ../.env/TOOLSTAT

# Basic controls
echo -n "-u" > ../.env/CMDUP
echo -n "-d" > ../.env/CMDDOWN
echo -n "-o" > ../.env/CMDONCE
echo -n "" > ../.env/CMDCHECK

# Unix-style signals
echo -n "-p" > ../.env/CMDPAUSE
echo -n "-c" > ../.env/CMDCONT
echo -n "-h" > ../.env/CMDHUP
echo -n "-a" > ../.env/CMDALRM
echo -n "-i" > ../.env/CMDINT
echo -n "-t" > ../.env/CMDTERM
echo -n "-k" > ../.env/CMDKILL
echo -n "-x" > ../.env/CMDEXIT

echo "done."
