#!/bin/sh

rm envdir && \
 ln -s /usr/bin/chpst ./envdir && \
  echo "$0: envdir reset"

rm envuidgid && \
 ln -s /usr/bin/chpst ./envuidgid && \
  echo "$0: envuidgid reset"

rm fghack && \
 ln -s /usr/bin/fghack ./fghack && \
  echo "$0: fghack reset"

rm pgrphack && \
 ln -s /usr/bin/chpst ./pgrphack && \
  echo "$0: pgrphack reset"

rm setlock && \
 ln -s /usr/bin/chpst ./setlock && \
  echo "$0: setlock reset"

rm setuidgid && \
 ln -s /usr/bin/chpst ./setuidgid && \
  echo "$0: setuidgid reset"

rm softlimit && \
 ln -s /usr/bin/chpst ./softlimit && \
  echo "$0: softlimit reset"

rm tai64n && \
 ln -s /usr/bin/tai64n ./tai64n && \
  echo "$0: tai64n reset"

rm tai64nlocal && \
 ln -s /usr/bin/tai64nlocal ./tai64nlocal && \
  echo "$0: tai64nlocal reset"

echo -n "$0: setting up framework-specific grammar, "
echo "runit" > ../.env/FRAMEWORK
echo -n "sv" > ../.env/TOOLCMD
echo -n "sv" > ../.env/TOOLCHECK
echo -n "sv" > ../.env/TOOLSTAT

# Basic controls
echo -n "up" > ../.env/CMDUP
echo -n "down" > ../.env/CMDDOWN
echo -n "once" > ../.env/CMDONCE
echo -n "check" > ../.env/CMDCHECK

# Unix-style signals
echo -n "pause" > ../.env/CMDPAUSE
echo -n "cont" > ../.env/CMDCONT
echo -n "hup" > ../.env/CMDHUP
echo -n "alarm" > ../.env/CMDALRM
echo -n "interrupt" > ../.env/CMDINT
echo -n "term" > ../.env/CMDTERM
echo -n "kill" > ../.env/CMDKILL
echo -n "quit" > ../.env/CMDEXIT

echo "done."

