#!/bin/sh
### BEGIN INIT INFO
# Provides:          aprsd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start aprsd daemon.
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/sbin/aprsd
NAME=aprsd

test -f $DAEMON || exit 0

case "$1" in

  start)
    update-inetd --disable ftp
    echo -n "Starting APRS gateway: "
    start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON -- -d
    echo "$NAME."
    ;;

  stop)
    echo -n "Stopping APRS gateway: "
    start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/$NAME.pid --exec $DAEMON
    echo "$NAME."
    ;;

  force-reload|restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    exit 1
    ;;

esac

exit 0
