#!/bin/sh

# redirect stderr to stdout
exec 2>&1

# shim our support tools into the path relative to the definition
PATH=$PWD/../.bin:$PATH

# checks required permissions and creates some missing directories
postfix check || exit 1

# $DAEMON, $DAEMONOPTS and $PRELAUNCH are defined in the local ./env diretory
exec envdir ../.env envdir ./env sh -c 'exec $PRELAUNCH $DAEMON $DAEMONOPTS'
