#!/bin/sh
exec 2>&1

# because Debian's init.d scripts silently exit when
# the service isn't installed, and we want to
# maintain backwards compat with init.d scripts, we
# will do the same (although it would be nice to
# not have to do this).
test -x /usr/sbin/ntpd || exit 5

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# if there are Debian environment settings, load them
[ -r /etc/default/ntp ]  && . /etc/default/ntp

# load additional options
[ -e /var/lib/ntp/ntp.conf.dhcp ] && NTPD_OPTS="$NTPD_OPTS -c /var/lib/ntp/ntp.conf.dhcp"

exec /usr/sbin/ntpd -u ntp:ntp -c /etc/ntpd.conf -f /var/lib/ntp/ntp.drift -p /var/run/ntpd.pid -n $NTPD_OPTS
