#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# redirect stderr to stdout...
exec 2>&1

# to ensure that all of the standard commands
# of daemontools are supported, intercept the
# path and give our local copy priority.  All
# of the symlinks in .bin point to their
# equivalent in whatever framework is installed,
# ensuring correct behavior.
PATH=../.bin:$PATH

# the daemon's name is the name of the script
DAEMON=$( basename $( pwd ) )

# attempt to load any Debian-specific environment
# settings from a control file.
[ -f /etc/default/$DAEMON ] && . /etc/default/$DAEMON

# if we have a set of daemon-specific options
# required to background the process, then load
# them from a local option file into DAEMONOPTS.
DAEMONOPTS=""
PRELAUNCH=""
[ -f ./options ] && . ./options

exec $PRELAUNCH $DAEMON $DAEMONOPTS
