#!/bin/sh

# redirect stderr to stdout...
exec 2>&1

# shim our support tools into the path
PATH=../.bin:$PATH

# the system default environment is defined in ../.env,
# $DAEMON, $DAEMONOPTS and $PRELAUNCH are defined in the local ./env diretory
exec envdir ../.env envdir ./env sh -c 'exec $PRELAUNCH $DAEMON $DAEMONOPTS '
