#!/bin/sh

# A minimalist getty launch script.
# Note that gettys run differently - they specify a tty to attach to.
# This means the link name is both the getty and the tty,
# and not just the service to run.  To use a specific getty
# you would specify the name, a dash, and the tty to control.

# Examples:
# mingetty for tty5 would be a soft link named "mingetty-tty5".
# agetty for tty3 would be a soft link named "agetty-tty3"
# fgetty for tty1 would be a soft link named "fgetty-tty1"

# The necessary options for each getty type are
# automatically determined by the THISGETTY variable
# which is passed into the local ./options file at
# runtime.  This may include such arcane things as baud rate, etc.

# to ensure that all of the standard commands
# of daemontools are supported, intercept the
# path and give our local copy priority.  All
# of the symlinks in .bin point to their
# equivalent in whatever framework is installed,
# ensuring correct behavior.
PATH=../.bin:$PATH

# the getty's name is the name of the directory
SOMEGETTY=$( basename $( pwd ) )

# split the getty program name off of the terminal name
THISGETTY=$(echo $SOMEGETTY | sed 's/-/ /' | awk '{ print $1 }' )
THISTTY=$(echo $SOMEGETTY | sed 's/-/ /' | awk '{ print $2 }' )

# getty options are fixed for each type, but still stored
# in the local options file.  This format has a postfix
# variable as well, for use with agetty, which wants something
# after the tty is specified.
$DAEMONOPTS=""
$PRELAUNCH=""
$SECONDARYOPTS=""
[ -f ./options ] && . ./options

exec $PRELAUNCH $THISGETTY $DAEMONOPTS $THISTTY $SECONDARYOPTS
