#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# redirect stderr to stdout...
exec 2>&1

# shim our support tools into the path
PATH=../.bin:$PATH

# look for a user ID
UID=""
if test -f ./env/UID ; then
  UID=$( cat ./env/UID )
fi

# if a run-state directory is defined, then build it prior to launch
if test -f ./env/STATEDIR ; then
  mkdir -p $( cat ./env/STATEDIR )
  chmod 755 $( cat ./env/STATEDIR )
  if test ! -z $UID ; then
    chown $UID $( cat ./env/STATEDIR )
  fi
fi

# the system default environment is defined in ../.env,
# $DAEMON, $DAEMONOPTS and $PRELAUNCH are defined in the local ./env diretory
exec envdir ../.env envdir ./env sh -c 'exec $PRELAUNCH $DAEMON $DAEMONOPTS '
