#!/bin/sh
exec 2>&1

# determine our parent's name
SVNAME=$( basename $( echo `pwd` | sed 's/log//' ) )

# set log directory
LOGDIR=$( cat ../../.env/LOGDIR )

# fallback for compatibility
[ -z $LOGDIR ] && LOGDIR=/var/log

# bring up svlogd logging into a subdirectory that has the parent's name.
[ -d $LOGDIR/$SVNAME ] || mkdir -p $LOGDIR/$SVNAME ; chown :adm $LOGDIR/$SVNAME
[ -d main ] || ln -s $LOGDIR/$SVNAME main
exec /usr/bin/svlogd -tt main

