#!/bin/sh
# Reference: http://skarnet.org/software/s6/s6-log.html
exec 2>&1

# determine our parent's name
SVNAME=$( basename $( echo `pwd` | sed 's/log//' ) )

# set log directory
LOGDIR=$( cat ../../.env/LOGDIR )

# fallback for compatibility
[ -z $LOGDIR ] && LOGDIR=/var/log

# bring up s6-log, logging into a directory that has the parent's name.
[ -d $LOGDIR/$SVNAME ] || mkdir -p $LOGDIR/$SVNAME ; chown :adm $LOGDIR/$SVNAME
[ -d main ] || ln -s $LOGDIR/$SVNAME main
exec /usr/bin/s6-log -b n15 s1048576 S16777216 l16738 r1000 T ./main
