#!/bin/sh

test -f /etc/default/autofs && . /etc/default/autofs
test -f /etc/sysconfig/autofs && . /etc/sysconfig/autofs
test -n "$TIMEOUT" && daemonoptions="--timeout=$TIMEOUT $daemonoptions"

# Check if NIS is up. If it's not installed, this will fail,
# and run automount anyway to handle non-NIS based maps.
sv check ypbind

exec /usr/sbin/automount -f $daemonoptions >/dev/null 2>&1
